// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function ExplainText(arg1:string):Promise<ai.ExplanationResponse>;
